services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-verification-api
    env_file:
      - .env
    volumes:
      - model_cache:/root/.cache:rw
      - logs:/app/logs:rw
      - temp:/app/temp:rw
    ports:
      - "8001:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  nginx:
    image: nginx:alpine
    container_name: id-verification-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  model_cache:
    driver: local
  logs:
    driver: local
  temp:
    driver: local