services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-verification-api
    env_file:
      - .env
    volumes:
      - model_cache:/root/.cache
      - ./logs:/app/logs
      - ./temp:/app/temp
    ports:
      - "8001:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    container_name: id-verification-nginx
    ports:
      - "8081:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    restart: unless-stopped

volumes:
  model_cache:
    driver: local